### ISSUE TITLE
C bindings

### ISSUE THREAD

**Issue by liamdiprose** [canselcik/libremarkable#112]
I'd like to wrap this library for Racket.

Is there any interest in adding C bindings to libremarkable?

**Comment by EnderKill98** [comment]
I don't think there is any interest currently.

It should be pretty doable though. I see two ways for that

## Approach 1: Wrapper Rust Lib that exports wrapped functions to C

However it should not be too hard to make a wrapper project that simply exposes things as C functions. Depending on what functionality is needed it should be easy enough to do, however to cover most of the features would probably mean a lot of porting and wrapping types etc.

Here is a good primer that explains how a rust project can export C functions and build a shared object file: https://docs.rust-embedded.org/book/interoperability/rust-with-c.html  
There may also be some libs that can automate it (not really looked to deep into that direction, however for C -> Rust there is [bindgen](https://crates.io/crates/bindgen)).

I can draft a minimal project that can do that, but I don't have the capacity to make a C Lib that cover a substantial area of the functionality of this rust lib.

## Approach 2: Use the old c implementation

This repo also has [a branch that preserves the old c implementation](https://github.com/canselcik/libremarkable/tree/legacy-c-impl) I'm not familiar with it, but I think it was the initial project of the lib. There are likely a lot of features missing, but together with [remarkable2-framebuffer](github.com/ddvk/remarkable2-framebuffer/) I'd assume that you could use that to get the core functionality running with that.

Maybe this approach might be the fastest to get going.

**Comment by LinusCDE** [comment]
I don't think there is any interest currently.

It should be pretty doable though. I see two ways for that

## Approach 1: Wrapper Rust Lib that exports wrapped functions to C

However it should not be too hard to make a wrapper project that simply exposes things as C functions. Depending on what functionality is needed it should be easy enough to do, however to cover most of the features would probably mean a lot of porting and wrapping types etc.

Here is a good primer that explains how a rust project can export C functions and build a shared object file: https://docs.rust-embedded.org/book/interoperability/rust-with-c.html  

I can draft a minimal project that can do that, but I don't have the capacity to make a C Lib that cover a substantial area of the functionality of this rust lib.

There also seems to be a lib that will then automate generating proper header files (the reverse of bindgen): https://github.com/mozilla/cbindgen

## Approach 2: Use the old c implementation

This repo also has [a branch that preserves the old c implementation](https://github.com/canselcik/libremarkable/tree/legacy-c-impl/legacy-c-impl) I'm not familiar with it, but I think it was the initial project of the lib. There are likely a lot of features missing, but together with [remarkable2-framebuffer](github.com/ddvk/remarkable2-framebuffer/) I'd assume that you could use that to get the core functionality running with that.

Maybe this approach might be the fastest to get going.

**Comment by liamdiprose** [comment]
Hi @LinusCDE,

Thanks for your detailed reply. I'm thinking of using Approach 1. For some reason I thought the work could only be done in this repository. I'm happy to start the repository if you don't. What do you think of "libremarkable-c"?

**Comment by EnderKill98** [comment]
Sure I don't mind.

Any objections regarding the name, @fenollp, @bkirwi ?

**Comment by liamdiprose** [comment]
Feel free to reach out in the issues.

https://github.com/liamdiprose/libremarkable-c
