### ISSUE TITLE
Battery location has changed in 1.8

### ISSUE THREAD

**Issue by Eeems** [canselcik/libremarkable#24]
In 1.8 the battery location has changed to `/sys/class/power_supply/bq27441-0`

**Comment by canselcik** [comment]
Hey @Eeems, thanks for bringing this up.

If you would be interested, you can open a PR addressing this by looking for it in the new location first, only to fall back to the old location if the new one results in a `ENOENT`. I would be more than happy to merge this.

**Comment by Eeems** [comment]
When I get the chance to mess around with the rust side of my project I'll make sure to open a PR 😄
