### ISSUE TITLE
Demo crash at launch

### ISSUE THREAD

**Issue by parzivail** [canselcik/libremarkable#30]
reMarkable version 2.1.1.3

	remarkable: ~/ wget https://github.com/canselcik/libremarkable/releases/download/0.3.2/demo
	Connecting to github.com (140.82.114.3:443)
	wget: note: TLS certificate validation not implemented
	Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.217.37.68:443)
	demo                 100% |********************************| 35.4M  0:00:00 ETA
	remarkable: ~/ chmod +x demo
	remarkable: ~/ systemctl stop xochitl
	remarkable: ~/ ./demo
	thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to open file: No such file or directory (os error 2)"', libcore/result.rs:945:5
	note: Run with `RUST_BACKTRACE=1` for a backtrace.
	remarkable: ~/ export RUST_BACKTRACE=1 && ./demo
	thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to open file: No such file or directory (os error 2)"', libcore/result.rs:945:5
	stack backtrace:
	0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
				at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
	1: std::sys_common::backtrace::print
				at libstd/sys_common/backtrace.rs:71
				at libstd/sys_common/backtrace.rs:59
	2: std::panicking::default_hook::{{closure}}
				at libstd/panicking.rs:211
	3: std::panicking::default_hook
				at libstd/panicking.rs:227
	4: std::panicking::rust_panic_with_hook
				at libstd/panicking.rs:511
	5: std::panicking::continue_panic_fmt
				at libstd/panicking.rs:426
	6: rust_begin_unwind
				at libstd/panicking.rs:337
	7: core::panicking::panic_fmt
				at libcore/panicking.rs:92
	8: core::result::unwrap_failed
				at /checkout/src/libcore/macros.rs:26
	9: demo::main
				at /checkout/src/libcore/result.rs:782
				at examples/demo.rs:1033
	10: std::rt::lang_start::{{closure}}
				at /checkout/src/libstd/rt.rs:74
	11: std::panicking::try::do_call
				at libstd/rt.rs:59
				at libstd/panicking.rs:310
	12: __rust_maybe_catch_panic
				at libpanic_unwind/lib.rs:105
	13: std::panicking::try
				at libstd/panicking.rs:289
	14: std::rt::lang_start_internal
				at libstd/panic.rs:392
				at libstd/rt.rs:58
	15: main
	16: __libc_start_main

I assume this is operator error, can you point me in the right direction?

**Comment by fenollp** [comment]
I believe that release link is of a build that looks for the wrong libc.so version. 

The demo definitely works when building from source. I suggest going the `cross` way as described in the readme as it’s the simplest way.

**Comment by parzivail** [comment]
Perfect, thank you.
