### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by vmx** [canselcik/libremarkable#31]
Could you please release a new version?

I've built a minimal example, which works when I point to master, but it doesn't compile with the released v0.3.2.

**Comment by canselcik** [comment]
Hey,

Published the current HEAD of master as v0.4.0. Feel free to close if this helped. Let me know if you need something else.

**Comment by vmx** [comment]
It's really strange and doesn't make sense at all. When I build my hello world application with HEAD it works, if I switch to the 0.4 release it panics with `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrUnaligned', /cargo/registry/src/github.com-1ecc6299db9ec823/libremarkable-0.4.0/src/framebuffer/core.rs:67:23`

I've tried it several times to recompile, also with `rm -Rf Cargo.lock target` in between. I can reproduce this behaviour every time.

It's late here, I'll have a closer look what the problem/differences in the source is some other time.

**Comment by fenollp** [comment]
This is the exact issue that building with LTO fixes ;)

**Comment by vmx** [comment]
> This is the exact issue that building with LTO fixes ;)

Both times it was built with the same Cargo.toml settings. I only changed the dependency from a released version to a GitHub URL and back.

**Comment by vmx** [comment]
This must be some of env issue on my machine. I use `cross` to compile and it must cache something or so. If I build the exact same code from within another directory it works. Thanks for the release.
