### ISSUE TITLE
tag HEAD results in Git warnings

### ISSUE THREAD

**Issue by vmx** [canselcik/libremarkable#36]
The latest release has Git tag `HEAD`. This leads to a warning when using Git. Example (after a fresh checkout):

```console
$ git status
warning: refname 'HEAD' is ambiguous.
warning: refname 'HEAD' is ambiguous.
```

I suggest deleting the `HEAD` tag and adding the `0.4.1` tag instead.

**Comment by canselcik** [comment]
Thanks for the report. Looks like I had somehow managed to create a tag with the name `HEAD` via the GitHub UI.

Should be fixed now. Give it a try and feel free to close or comment.

**Comment by vmx** [comment]
I tried, it's fixed now. Thanks for being so quick!
