### ISSUE TITLE
Suggestion: use "config.mk" model for easily customizing build flags

### ISSUE THREAD

**Issue by PaulBatchelor** [canselcik/libremarkable#5]
A configuration file for Make would be a nice thing to have. I thought I would run it by you before making a PR.

For me, this would be necessary because my cross-compiler toolchains are in weird, non-standard locations. 

The classic example of this is with [dwm](https://github.com/sr/dwm). I would probably implement something similar to my own projects [Soundpipe](https://github.com/paulbatchelor/soundpipe) and [Sporth](https://github.com/paulbatchelor/sporth). 

What do you think?

**Comment by canselcik** [comment]
Yeah I wouldn't be against it. You can definitely focus on improving the config and build steps of the C implementation. There also might be some value in making it download and extract the Poky Toolchain before a build, or at least check if `arm-linux-gnueabihf-gcc` exists and can be used to build executables.

**Comment by PaulBatchelor** [comment]
>  download and extract Poky Toolchain before a build

It would be cleaner to put this in a shell script that the user explicitly calls rather than try to have Make do  that.

> or at least check if arm-linux-gnueabihf-gcc exists

The `?=` operator should do the job, as it will set `CC` to that value by default unless overwritten. A config file could override those defaults too.

**Comment by PatrickGretzki** [comment]
Its seems, that the "nightly" channel is needed for compiling the rust example ... otherwise "mock_derive" won't compile

**Comment by canselcik** [comment]
@PatrickGretzki Thanks for pointing that out. All the `mock`ing code was introduced with https://github.com/canselcik/libremarkable/commit/517a0445ecdce63df4eacd6d60904286ee7d559c, you can do `git revert 517a044` as a temporary workaround (or use the nightly channel) as we aren't even leveraging these mocking capabilities yet.

Let me know if you have further comments/suggestions, especially since `PatrickGretzki/paperOS` looks like we have quite an overlap there. :)

**Comment by PatrickGretzki** [comment]
I just started using rust, so I will have many questions in the next days :)
Otherwise regarding "PaperOS" - in the moment I try to collect ideas and features for a smart replacement of "xochitl". As soon as the concept is ready and I tested some design issues, we should work together to make it reality.

**Comment by PatrickGretzki** [comment]
Hey. its me again- The cross-compiler is running and I can compile simple programs for the remarkable. But  building your example/lib is still not working. The package "lua52-sys" throws a panic error at compiling 
`Compiling lua52-sys v0.1.1`
`error: failed to run cusom build command for 'lua52-sys v0.1.1`
`process didn't exit successfully `
`[...]`
`Internal error occurred: Failed to find tool. Is 'cortexa9hf-neon-poky-linux-gnueabihf' installed?`
`~/.cargo/registry/src/.../gcc-0.3.54/src/lib.rs:1670:5``

Any ideas guys ?

**Comment by canselcik** [comment]
@PatrickGretzki Do you have the toolchain installed? What platform are you building on? Linux, OS or Windows?

I can help you through all the build issues. Let me know.

**Comment by canselcik** [comment]
You can also see my latest commit https://github.com/canselcik/libremarkable/commit/e48f949efa41bb81a1187d22492f7cf105a75312 which should take care of the `nightly` requirement due to `mock_derive`.

**Comment by PatrickGretzki** [comment]
Okay - Today  I started from scratch to ensure, that I can reproduce the error and have a stable environment. I did not use the "poky" tool chain but the default arm-gcc.

**- Install minimal ubuntu linux image in VM**
`http://de.releases.ubuntu.com/artful/ubuntu-17.10.1-server-i386.iso`

**- Install Rust**
`curl https://sh.rustup.rs -sSf | sh`

**- Setup rust for nightly channel**
`curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly`
`rustup install nightly`
`rustup default nightly`

**- Install cross-compiler toolchain**
`sudo apt-get install -qq gcc-arm-linux-gnueabihf`

**- Install cross compiled standard crates**
`rustup target add armv7-unknown-linux-gnueabihf`

**- Configure cargo for cross compilation**
`mkdir -p ~/.cargo`
`touch ~/.cargo/config`
`cat >>~/.cargo/config <<EOF`
`[target.armv7-unknown-linux-gnueabihf]`
`linker = "arm-linux-gnueabihf-gcc"`
`EOF`

**- Test cross-compiler with empty project**
`cargo new --bin dummy`
`cd dummy`
`cargo build --release --target=armv7-unknown-linux-gnueabihf`

**- Clone repository and compile**
`git clone https://github.com/canselcik/libremarkable.git
`make`


So ... the cross-compiler is working for a simple "hello world". For your project I had some minor drawbacks. The nightly build is a must. Also you need the package "gcc" for building some crates (e.g. "regex"). Now everything is working fine - Thanks !

**Comment by canselcik** [comment]
Awesome. Glad to hear that @PatrickGretzki. Thanks for the detailed description of the steps you had to follow. I will include them in the wiki later today once I have some free time.

In the meantime, if you haven't looked at all the pages on the wiki, I definitely recommend it. It has a lot of fresh information.

https://github.com/canselcik/libremarkable/wiki

**Comment by canselcik** [comment]
Also @PatrickGretzki since you are one of the first people I know that ran the demo example on his device, here are some interesting features you might want to try:

Pressing the MIDDLE button will clear the lower half of the screen.
Pressing the LEFT button will toggle the `touch action` between: `none`, `circles` and `bezier`.
Pressing the RIGHT button will draw a black rectangle on the screen for as long as the button is kept pressed.

**Comment by vsenderov** [comment]
Hello,
After following this procedure, I get an error in the last step (`make`). Make system is Ubuntu 19.10. Any help will be appreciated. Output included:

```
$ make 
cargo build --release --target=armv7-unknown-linux-gnueabihf
   Compiling autocfg v1.0.0
   Compiling libc v0.2.69
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling rand_core v0.4.2
   Compiling autocfg v0.1.7
   Compiling byteorder v1.3.4
   Compiling maybe-uninit v2.0.0
   Compiling proc-macro2 v0.4.30
   Compiling scopeguard v1.1.0
   Compiling rustc-serialize v0.3.24
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.44
   Compiling memchr v2.3.3
   Compiling rayon-core v1.7.0
   Compiling glob v0.3.0
   Compiling bitflags v1.2.1
   Compiling adler32 v1.0.4
   Compiling num-derive v0.2.5
   Compiling pkg-config v0.3.17
   Compiling log v0.4.8
   Compiling lzw v0.10.0
   Compiling either v1.5.3
   Compiling regex-syntax v0.6.17
   Compiling cgmath v0.17.0
   Compiling color_quant v1.0.1
   Compiling bitflags v0.7.0
   Compiling remove_dir_all v0.5.2
   Compiling quick-error v1.2.3
   Compiling void v1.0.2
   Compiling termcolor v1.1.0
   Compiling scoped_threadpool v0.1.9
   Compiling fixedbitset v0.1.9
   Compiling libc v0.1.12
   Compiling fnv v1.0.6
   Compiling bitflags v0.8.2
   Compiling ioctl-gen v0.1.1
   Compiling atomic v0.4.5
   Compiling thread_local v1.0.1
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling inflate v0.4.5
   Compiling gif v0.10.3
   Compiling humantime v1.3.0
   Compiling aabb-quadtree v0.1.0
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.4
   Compiling num-iter v0.1.40
   Compiling crossbeam-epoch v0.8.2
   Compiling num-rational v0.2.4
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling aho-corasick v0.7.10
   Compiling quote v0.6.13
   Compiling rand v0.4.6
   Compiling num_cpus v1.13.0
   Compiling rand_os v0.1.3
   Compiling atty v0.2.14
   Compiling nix v0.8.1
   Compiling epoll v4.1.0
   Compiling jobserver v0.1.21
   Compiling deflate v0.7.20
   Compiling stb_truetype v0.3.1
   Compiling cc v1.0.52
   Compiling tempdir v0.3.7
   Compiling regex v1.3.7
   Compiling num-complex v0.1.43
   Compiling approx v0.3.2
   Compiling ordered-float v1.0.2
   Compiling num-traits v0.1.43
   Compiling mmap v0.1.1
   Compiling crossbeam-queue v0.2.1
   Compiling num-bigint v0.1.44
   Compiling line_drawing v0.8.0
   Compiling rusttype v0.8.3
   Compiling png v0.14.1
   Compiling env_logger v0.7.1
   Compiling crossbeam-deque v0.7.3
   Compiling num-rational v0.1.42
   Compiling num v0.1.42
   Compiling rayon v1.3.0
   Compiling stopwatch v0.0.7
   Compiling evdev v0.10.1
   Compiling zstd-sys v1.4.15+zstd.1.4.4
   Compiling lua52-sys v0.1.2
   Compiling jpeg-decoder v0.1.19
   Compiling hlua v0.4.1
   Compiling tiff v0.2.2
   Compiling image v0.21.3
   Compiling zstd-safe v2.0.3+zstd.1.4.4
   Compiling zstd v0.5.1+zstd.1.4.4
   Compiling libremarkable v0.3.2 (/home/viktsend/Programs/libremarkable)
    Finished release [optimized + debuginfo] target(s) in 52.28s
cargo build --examples --release --target=armv7-unknown-linux-gnueabihf
   Compiling smallvec v1.4.0
   Compiling matches v0.1.8
   Compiling percent-encoding v1.0.1
   Compiling ascii v0.8.7
   Compiling chunked_transfer v0.3.1
   Compiling time v0.1.43
   Compiling redhook v1.0.0
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling chrono v0.4.11
   Compiling idna v0.1.5
   Compiling url v1.7.2
   Compiling tiny_http v0.6.2
   Compiling libremarkable v0.3.2 (/home/viktsend/Programs/libremarkable)
warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
   --> examples/spy.rs:106:1
    |
106 | / hook! {
107 | |   unsafe fn ioctl(fd: c_int, request: NativeWidthType, p1: intptr_t, p2: intptr_t, p3: intptr_t, p4: intptr_t) -> c_int => ioctl_hook {
108 | |     if request == FBIOPUT_VSCREENINFO {
109 | |         let info = p1 as *mut VarScreeninfo;
...   |
142 | |   }
143 | | }
    | |_^
    |
    = note: `#[warn(deprecated)]` on by default
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
   --> examples/spy.rs:106:1
    |
106 | / hook! {
107 | |   unsafe fn ioctl(fd: c_int, request: NativeWidthType, p1: intptr_t, p2: intptr_t, p3: intptr_t, p4: intptr_t) -> c_int => ioctl_hook {
108 | |     if request == FBIOPUT_VSCREENINFO {
109 | |         let info = p1 as *mut VarScreeninfo;
...   |
142 | |   }
143 | | }
    | |_^
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: lto can only be run for executables, cdylibs and static library outputs

error: aborting due to previous error; 2 warnings emitted

error: could not compile `libremarkable`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:7: examples] Error 101


```
