### ISSUE TITLE
Compilation Error with EvDev (Mismatch types)

### ISSUE THREAD

**Issue by rlingineni** [canselcik/libremarkable#57]
I was following the instructions to build with `musl`.

However, there seems to be a compile error. Building on MacOS.

```
Compiling evdev v0.10.2
convert_ioctl_res!(::nix::libc::ioctl(fd, ior!(b'E', 0x20 + ev, len) as ::libc::c_ulong, buf))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
```
I'm new to the lang, but it seems the error might be due to this issue: https://github.com/emberian/evdev/issues/22 

Looks like the newest version hasn't been published with the fix

**Comment by bkirwi** [comment]
Fixed now that the linked PR is merged... thanks for the report!
