### ISSUE TITLE
Power - turn off the screen?

### ISSUE THREAD

**Issue by darvin** [canselcik/libremarkable#7]
Do you know if there is a way to turn off the screen?

for example, kobo readers turn it off by writing into file:

echo 1 > /sys/power/state-extended

**Comment by canselcik** [comment]
Hi,

Disabling EPDC access by calling `DISABLE_EPDC_ACCESS` should be able to achieve that.

See here:
https://docs.rs/libremarkable/0.1.26/libremarkable/framebuffer/trait.FramebufferBase.html#tymethod.set_epdc_access

There is also the auto-powerdown delay, which allows the EPD to be powered down when an update hasn't been pushed to it for a while.

See here for that:
https://github.com/canselcik/libremarkable/blob/master/reference-material/mxcfb.h#L193-L194

And here for the implementation of the powerdown:
https://github.com/canselcik/libremarkable/blob/master/reference-material/mxc_epdc_fb.c#L3672-L3678

**Comment by darvin** [comment]
thanks!

**Comment by canselcik** [comment]
No problem. Feel free to create another issue for further questions.
