### ISSUE TITLE
0.5.0 release

### ISSUE THREAD

**Issue by akdor1154** [canselcik/libremarkable#77]
Hey guys, 
I think i just got unlucky and pulled this at the wrong hour, but it looks like something is funny with the 0.5.0 release.
Crates.io was published 9 days ago, but the Cargo.toml only got bumped to 0.5.0 today, and deps of crate are older than deps in the commit containing 0.5.0 version bump.

**Comment by bkirwi** [comment]
I suspect this is my fault... I did the 0.5.0 release, and it looks like I failed to push the actual version-bump commit up to the main repository. Apologies! (The 0.5.0 release is commit b5a0ea1c1ef39c70dfbcb8982a34ebb2afd91575, if that helps any.)

Does this cause issues for you in practice?

**Comment by akdor1154** [comment]
Ah ta. No not directly -it seemed like it at the time, but i was looking to fix some dep issues and the release vs. repo state was just a red herring. Thanks for your work on this project :)

**Comment by bkirwi** [comment]
Aight, I've now merged so that this commit is visible on the `master` branch. (It sounds like it's not causing issues, but hopefully that will avoid more confusion.) Thanks for checking in!
