### ISSUE TITLE
Make Lua optional

### ISSUE THREAD

**Issue by LoganDark** [canselcik/libremarkable#86]
Including Lua is wasted space when it's not used, please put it behind a Cargo feature (even if that's enabled by default). Honestly most of the crate should be behind cargo features.

**Comment by fenollp** [comment]
Hi @LoganDark thanks for raising this. 
We appreciate your comment and welcome discussion. cc at https://github.com/canselcik/libremarkable/pull/55

Can you tell us a bit more about how you're using libremarkable?

What other parts of the crate do you feel should be behind features?

**Comment by LoganDark** [comment]
> Can you tell us a bit more about how you're using libremarkable?

I'm going to use libremarkable in 2 programs that are designed to work together:

- An application that the user runs to input calibration data. This will require the GUI stuff, but not Lua
- A shared object that intercepts xochitl's pen events, ReCept-style. This does NOT require the GUI stuff, only the input device scanning (so I know which /dev/input/eventX is the wacom digitizer)

In the former case I need the entire application system, input event handling and all. But in the latter case I only need a small subset of libremarkable.

**Comment by bkirwi** [comment]
Yeah, I think this use case is addressed by #55. (Which we don't have an issue for yet, so might as well keep this one open.)

It's worth mentioning that `appctx` is not very heavily used, compared to the rest of the library. Many `libremarkable` users end up using the low-level device support and handrolling a toolkit suited to the needs of their app. If you're not happy with how appctx works, that's a good way to keep yourself unblocked! (Though we should follow through on #55 regardless to keep builds lighter.)

**Comment by bkirwi** [comment]
#55 is merged, so I'll mark this done. We should have a proper release out soon within the next week or two I imagine...
